[phases.setup]
nixPkgs = ["nodejs_18", "chromium", "nss", "freetype", "freetype-dev", "harfbuzz", "ca-certificates", "ttf_fonts"]

[phases.install]
cmds = [
  "npm ci --only=production"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium-*/bin/chromium"
